#!/usr/bin/env python3

fname = "NIRCam_SIAF.csv"
fp = open(fname)
fl = fp.readlines()

i = 0
for l in fl:
	if(i==1):
		print(l.strip('\n').split(','))

	if( ((i>=14)&(i<=18))|((i>=20)&(i<=24)) ):
		print(i,len(l.split(',')))
		print(l.split(',')[0:5])
		k = 1
		AperName = (fl[1].strip('\n').split(',')[k])
		AperVal  = (l.strip('\n').split(',')[k])
		k+=4
		XDetSize  = (fl[1].strip('\n').split(',')[k])
		XDetSizeV = (l.strip('\n').split(',')[k])
		k+=1
		YDetSize  = (fl[1].strip('\n').split(',')[k])
		YDetSizeV = (l.strip('\n').split(',')[k])
		k+=1
		XDetRef  = (fl[1].strip('\n').split(',')[k])
		XDetRefV = (l.strip('\n').split(',')[k])
		k+=1
		YDetRef  = (fl[1].strip('\n').split(',')[k])
		YDetRefV = (l.strip('\n').split(',')[k])
		k+=1
		XSciSize  = (fl[1].strip('\n').split(',')[k])
		XSciSizeV = (l.strip('\n').split(',')[k])
		k+=1
		YSciSize  = (fl[1].strip('\n').split(',')[k])
		YSciSizeV = (l.strip('\n').split(',')[k])
		k+=1
		XSciRef  = (fl[1].strip('\n').split(',')[k])
		XSciRefV = (l.strip('\n').split(',')[k])
		k+=1
		YSciRef  = (fl[1].strip('\n').split(',')[k])
		YSciRefV = (l.strip('\n').split(',')[k])
		k+=1
		XSciScale  = (fl[1].strip('\n').split(',')[k])
		XSciScaleV = (l.strip('\n').split(',')[k])
		k+=1
		YSciScale  = (fl[1].strip('\n').split(',')[k])
		YSciScaleV = (l.strip('\n').split(',')[k])
		k+=1
		V2Ref  = (fl[1].strip('\n').split(',')[k])
		V2RefV = (l.strip('\n').split(',')[k])
		k+=1
		V3Ref  = (fl[1].strip('\n').split(',')[k])
		V3RefV = (l.strip('\n').split(',')[k])
		k+=1
		V3IdlYAngle  = (fl[1].strip('\n').split(',')[k])
		V3IdlYAngleV = (l.strip('\n').split(',')[k])
		k+=1
		VIdlParity  = (fl[1].strip('\n').split(',')[k])
		VIdlParityV = (l.strip('\n').split(',')[k])	
		k+=1
		DetSciYAngle  = (fl[1].strip('\n').split(',')[k])
		DetSciYAngleV = (l.strip('\n').split(',')[k])	
		k+=1
		DetSciParity  = (fl[1].strip('\n').split(',')[k])
		DetSciParityV = (l.strip('\n').split(',')[k])	
		k+=1
		V3SciXAngle  = (fl[1].strip('\n').split(',')[k])
		V3SciXAngleV = (l.strip('\n').split(',')[k])	
		k+=1
		V3SciYAngle  = (fl[1].strip('\n').split(',')[k])
		V3SciYAngleV = (l.strip('\n').split(',')[k])	
		k+=11	
		Sci2IdlDeg  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlDegV = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX00  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX00V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX10  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX10V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX11  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX11V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX20  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX20V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX21  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX21V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX22  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX22V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX30  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX30V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX31  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX31V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX32  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX32V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX33  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX33V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX40  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX40V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX41  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX41V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX42  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX42V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX43  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX43V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX44  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX44V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX50  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX50V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX51  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX51V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX52  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX52V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX53  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX53V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX54  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX54V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlX55  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlX55V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY00  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY00V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY10  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY10V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY11  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY11V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY20  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY20V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY21  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY21V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY22  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY22V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY30  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY30V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY31  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY31V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY32  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY32V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY33  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY33V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY40  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY40V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY41  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY41V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY42  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY42V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY43  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY43V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY44  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY44V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY50  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY50V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY51  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY51V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY52  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY52V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY53  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY53V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY54  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY54V = (l.strip('\n').split(',')[k])
		k+=1 
		Sci2IdlY55  = (fl[1].strip('\n').split(',')[k])
		Sci2IdlY55V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX00  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX00V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX10  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX10V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX11  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX11V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX20  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX20V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX21  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX21V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX22  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX22V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX30  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX30V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX31  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX31V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX32  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX32V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX33  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX33V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX40  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX40V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX41  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX41V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX42  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX42V = (l.strip('\n').split(',')[k])
		k+=1
		Idl2SciX43  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX43V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX44  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX44V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX50  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX50V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX51  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX51V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX52  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX52V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX53  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX53V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX54  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX54V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciX55  = (fl[1].strip('\n').split(',')[k])
		Idl2SciX55V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY00  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY00V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY10  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY10V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY11  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY11V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY20  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY20V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY21  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY21V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY22  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY22V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY30  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY30V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY31  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY31V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY32  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY32V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY33  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY33V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY40  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY40V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY41  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY41V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY42  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY42V = (l.strip('\n').split(',')[k])
		k+=1
		Idl2SciY43  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY43V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY44  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY44V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY50  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY50V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY51  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY51V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY52  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY52V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY53  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY53V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY54  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY54V = (l.strip('\n').split(',')[k])
		k+=1 
		Idl2SciY55  = (fl[1].strip('\n').split(',')[k])
		Idl2SciY55V = (l.strip('\n').split(',')[k])
		k+=1 
		s =  "{'%s':'%s'," % (AperName,AperVal)
		s += "'%s':%s,"  % (XDetSize,XDetSizeV)
		s += "'%s':%s,"  % (YDetSize,YDetSizeV)
		s += "'%s':%s,"  % (XDetRef,XDetRefV)
		s += "'%s':%s,"  % (YDetRef,YDetRefV)
		s += "'%s':%s,"  % (XSciSize,XSciSizeV)
		s += "'%s':%s,"  % (YSciSize,YSciSizeV)
		s += "'%s':%s,"  % (XSciRef,XSciRefV)
		s += "'%s':%s,"  % (YSciRef,YSciRefV)
		s += "'%s':%s,"  % (XSciScale,XSciScaleV)
		s += "'%s':%s,"  % (YSciScale,YSciScaleV)
		s += "'%s':%s,"  % (V2Ref,V2RefV)
		s += "'%s':%s,"  % (V3Ref,V3RefV)
		s += "'%s':%s,"  % (V3IdlYAngle,V3IdlYAngleV)
		s += "'%s':%s,"  % (VIdlParity,VIdlParityV)
		s += "'%s':%s,"  % (DetSciYAngle,DetSciYAngleV)
		s += "'%s':%s,"  % (DetSciParity,DetSciParityV)
		s += "'%s':%s,"  % (V3SciXAngle,V3SciXAngleV)
		s += "'%s':%s,"  % (V3SciYAngle,V3SciYAngleV)
		s += "'%s':%s,"  % (Sci2IdlDeg,Sci2IdlDegV)
		s += "'%s':%s,"  % (Sci2IdlX00,Sci2IdlX00V)
		s += "'%s':%s,"  % (Sci2IdlX10,Sci2IdlX10V)
		s += "'%s':%s,"  % (Sci2IdlX11,Sci2IdlX11V)
		s += "'%s':%s,"  % (Sci2IdlX20,Sci2IdlX20V)
		s += "'%s':%s,"  % (Sci2IdlX21,Sci2IdlX21V)
		s += "'%s':%s,"  % (Sci2IdlX22,Sci2IdlX22V)
		s += "'%s':%s,"  % (Sci2IdlX30,Sci2IdlX30V)
		s += "'%s':%s,"  % (Sci2IdlX31,Sci2IdlX31V)
		s += "'%s':%s,"  % (Sci2IdlX32,Sci2IdlX32V)
		s += "'%s':%s,"  % (Sci2IdlX33,Sci2IdlX33V)
		s += "'%s':%s,"  % (Sci2IdlX40,Sci2IdlX40V)
		s += "'%s':%s,"  % (Sci2IdlX41,Sci2IdlX41V)
		s += "'%s':%s,"  % (Sci2IdlX42,Sci2IdlX42V)
		s += "'%s':%s,"  % (Sci2IdlX43,Sci2IdlX43V)
		s += "'%s':%s,"  % (Sci2IdlX44,Sci2IdlX44V)
		s += "'%s':%s,"  % (Sci2IdlX50,Sci2IdlX50V)
		s += "'%s':%s,"  % (Sci2IdlX51,Sci2IdlX51V)
		s += "'%s':%s,"  % (Sci2IdlX52,Sci2IdlX52V)
		s += "'%s':%s,"  % (Sci2IdlX53,Sci2IdlX53V)
		s += "'%s':%s,"  % (Sci2IdlX54,Sci2IdlX54V)
		s += "'%s':%s,"  % (Sci2IdlX55,Sci2IdlX55V)
		s += "'%s':%s,"  % (Sci2IdlY00,Sci2IdlY00V)
		s += "'%s':%s,"  % (Sci2IdlY10,Sci2IdlY10V)
		s += "'%s':%s,"  % (Sci2IdlY11,Sci2IdlY11V)
		s += "'%s':%s,"  % (Sci2IdlY20,Sci2IdlY20V)
		s += "'%s':%s,"  % (Sci2IdlY21,Sci2IdlY21V)
		s += "'%s':%s,"  % (Sci2IdlY22,Sci2IdlY22V)
		s += "'%s':%s,"  % (Sci2IdlY30,Sci2IdlY30V)
		s += "'%s':%s,"  % (Sci2IdlY31,Sci2IdlY31V)
		s += "'%s':%s,"  % (Sci2IdlY32,Sci2IdlY32V)
		s += "'%s':%s,"  % (Sci2IdlY33,Sci2IdlY33V)
		s += "'%s':%s,"  % (Sci2IdlY40,Sci2IdlY40V)
		s += "'%s':%s,"  % (Sci2IdlY41,Sci2IdlY41V)
		s += "'%s':%s,"  % (Sci2IdlY42,Sci2IdlY42V)
		s += "'%s':%s,"  % (Sci2IdlY43,Sci2IdlY43V)
		s += "'%s':%s,"  % (Sci2IdlY44,Sci2IdlY44V)
		s += "'%s':%s,"  % (Sci2IdlY50,Sci2IdlY50V)
		s += "'%s':%s,"  % (Sci2IdlY51,Sci2IdlY51V)
		s += "'%s':%s,"  % (Sci2IdlY52,Sci2IdlY52V)
		s += "'%s':%s,"  % (Sci2IdlY53,Sci2IdlY53V)
		s += "'%s':%s,"  % (Sci2IdlY54,Sci2IdlY54V)
		s += "'%s':%s,"  % (Sci2IdlY55,Sci2IdlY55V)
		s += "'%s':%s,"  % (Idl2SciX00,Idl2SciX00V)
		s += "'%s':%s,"  % (Idl2SciX10,Idl2SciX10V)
		s += "'%s':%s,"  % (Idl2SciX11,Idl2SciX11V)
		s += "'%s':%s,"  % (Idl2SciX20,Idl2SciX20V)
		s += "'%s':%s,"  % (Idl2SciX21,Idl2SciX21V)
		s += "'%s':%s,"  % (Idl2SciX22,Idl2SciX22V)
		s += "'%s':%s,"  % (Idl2SciX30,Idl2SciX30V)
		s += "'%s':%s,"  % (Idl2SciX31,Idl2SciX31V)
		s += "'%s':%s,"  % (Idl2SciX32,Idl2SciX32V)
		s += "'%s':%s,"  % (Idl2SciX33,Idl2SciX33V)
		s += "'%s':%s,"  % (Idl2SciX40,Idl2SciX40V)
		s += "'%s':%s,"  % (Idl2SciX41,Idl2SciX41V)
		s += "'%s':%s,"  % (Idl2SciX42,Idl2SciX42V)
		s += "'%s':%s,"  % (Idl2SciX43,Idl2SciX43V)
		s += "'%s':%s,"  % (Idl2SciX44,Idl2SciX44V)
		s += "'%s':%s,"  % (Idl2SciX50,Idl2SciX50V)
		s += "'%s':%s,"  % (Idl2SciX51,Idl2SciX51V)
		s += "'%s':%s,"  % (Idl2SciX52,Idl2SciX52V)
		s += "'%s':%s,"  % (Idl2SciX53,Idl2SciX53V)
		s += "'%s':%s,"  % (Idl2SciX54,Idl2SciX54V)
		s += "'%s':%s,"  % (Idl2SciX55,Idl2SciX55V)
		s += "'%s':%s,"  % (Idl2SciY00,Idl2SciY00V)
		s += "'%s':%s,"  % (Idl2SciY10,Idl2SciY10V)
		s += "'%s':%s,"  % (Idl2SciY11,Idl2SciY11V)
		s += "'%s':%s,"  % (Idl2SciY20,Idl2SciY20V)
		s += "'%s':%s,"  % (Idl2SciY21,Idl2SciY21V)
		s += "'%s':%s,"  % (Idl2SciY22,Idl2SciY22V)
		s += "'%s':%s,"  % (Idl2SciY30,Idl2SciY30V)
		s += "'%s':%s,"  % (Idl2SciY31,Idl2SciY31V)
		s += "'%s':%s,"  % (Idl2SciY32,Idl2SciY32V)
		s += "'%s':%s,"  % (Idl2SciY33,Idl2SciY33V)
		s += "'%s':%s,"  % (Idl2SciY40,Idl2SciY40V)
		s += "'%s':%s,"  % (Idl2SciY41,Idl2SciY41V)
		s += "'%s':%s,"  % (Idl2SciY42,Idl2SciY42V)
		s += "'%s':%s,"  % (Idl2SciY43,Idl2SciY43V)
		s += "'%s':%s,"  % (Idl2SciY44,Idl2SciY44V)
		s += "'%s':%s,"  % (Idl2SciY50,Idl2SciY50V)
		s += "'%s':%s,"  % (Idl2SciY51,Idl2SciY51V)
		s += "'%s':%s,"  % (Idl2SciY52,Idl2SciY52V)
		s += "'%s':%s,"  % (Idl2SciY53,Idl2SciY53V)
		s += "'%s':%s,"  % (Idl2SciY54,Idl2SciY54V)
		s += "'%s':%s,"  % (Idl2SciY55,Idl2SciY55V)

		print(s)
	i+=1